### PR TITLE
Migrated nf-present to sli.dev

### LINKED ISSUE #64: Replace nf-present with Slidev
At the moment, the GraphQL-workshop uses nf-present to build the slide-deck for presentation.

A Nearform [slidev ](https://sli.dev/)template is available [here](https://github.com/nearform/new-promises-workshop) which has better support for content formatting and already has NF design.

Migrate the GraphQL workshop from using nf-present to slidev

### PR DESCRIPTION
**Pull request by sameer-coder**
This PR changes the presentation format to use Nearform theme. `nf-present` presentation library is replaced with `sli.dev` library because it offers much customization options and the content fits better.

Closes #64

### CODE REVIEW

**Comment by hails** [comment]
Should the `dist` folder be committed? Otherwise we should remove it from the PR and also add it to the .gitignore file.

**Comment by galvez** [comment]
@sameer-coder this looks *really good* — just went through the slides, nice work.

**Comment by sameer-coder** [comment]
> @sameer-coder this looks _really good_ — just went through the slides, nice work.

@galvez  Thanks for the awesome theme!

**Comment by simoneb** [comment]
do we really need to commit 200+ files for this to work?

**Comment by hails** [comment]
When I run it locally I get the following issues:

The first slide is empty
image

No headers/titles
image
image

The same happens on both Safari and Google Chrome, I'm running it with `npm run start`

**Comment by galvez** [comment]
> The same happens on both Safari and Google Chrome, I'm running it with `npm run start`

I think it's probably because you have your dark mode preference off and it's displaying the light one.

We should force dark mode, this is a fix needed for the theme.

**Comment by simoneb** [comment]
> > do we really need to commit 200+ files for this to work?
> 
> That's because it includes the theme @simoneb — ideally the theme is extracted into a separate, reusable package.

@sameer-coder considering how many files this requires to be added to the repo, I would do that now.

**Review by katafira — APPROVED** [review]
Code looks OK.

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Pull request merged**
